# Generated by Django 5.1.7 on 2025-04-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Rank',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='middlename',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='totalmark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='rank',
            field=models.IntegerField(default=1000),
        ),
    ]
