# Generated by Django 5.1.7 on 2025-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_users_rank_users_email_users_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='correct',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
