# Generated by Django 5.1.7 on 2025-04-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_questions_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='qnumber',
            field=models.IntegerField(default=0),
        ),
    ]
